---
count: 4
default:
  restart: 0
  wait: 1
editor:
  files:
    take:
      - bin/git-take
      - lib/App/Git/Workflow/Command/Take.pm
      - t/take.t
name: git-take
terminals:
  1a:
    command: ./Build && ./Build testcover
    restart: 1
    wait: 0
    watch:
      - lib
      - bin
      - tests
  2:
    edit: take
  3: []

  4: []

